# Generated by Django 3.0 on 2019-12-09 16:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_auto_20191209_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='dateCreated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='todo',
            name='dateModified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='todo',
            name='deletedAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='deletedAt',
            field=models.DateTimeField(null=True),
        ),
    ]
