# Generated by Django 3.0 on 2019-12-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_auto_20191209_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='deletedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='deletedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
