# Generated by Django 3.0 on 2019-12-09 16:06

from django.db import migrations, models
import utils.random


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_auto_20191209_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='tid',
            field=models.IntegerField(blank=True, default=utils.random.genId, max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(blank=True, default=utils.random.genId, max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='userName',
            field=models.CharField(max_length=128),
        ),
    ]
