# Generated by Django 3.0 on 2019-12-25 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0008_auto_20191225_0828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locale',
            fields=[
                ('localName', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='todo',
            name='loc',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='todos.Locale'),
        ),
    ]
