# Generated by Django 3.0 on 2019-12-25 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0009_auto_20191225_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='loc',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Locale',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
